GEThttps://wordsapiv1.p.mashape.com/words/{word}/also
GEThttps://wordsapiv1.p.mashape.com/words/{word}/entails
GEThttps://wordsapiv1.p.mashape.com/words/{word}/hasCategories
GEThttps://wordsapiv1.p.mashape.com/words/{word}/hasInstances
GEThttps://wordsapiv1.p.mashape.com/words/{word}/hasMembers
GEThttps://wordsapiv1.p.mashape.com/words/{word}/hasParts
GEThttps://wordsapiv1.p.mashape.com/words/{word}/hasSubstances
GEThttps://wordsapiv1.p.mashape.com/words/{word}/hasTypes
GEThttps://wordsapiv1.p.mashape.com/words/{word}/hasUsages
GEThttps://wordsapiv1.p.mashape.com/words/{word}/inCategory
GEThttps://wordsapiv1.p.mashape.com/words/{word}/inRegion
GEThttps://wordsapiv1.p.mashape.com/words/{word}/typeOf
GEThttps://wordsapiv1.p.mashape.com/words/{word}/instanceOf
GEThttps://wordsapiv1.p.mashape.com/words/{word}/memberOf
GEThttps://wordsapiv1.p.mashape.com/words/{word}/partOf
GEThttps://wordsapiv1.p.mashape.com/words/{words}/pertainsTo
GEThttps://wordsapiv1.p.mashape.com/words/{word}/regionOf
GEThttps://wordsapiv1.p.mashape.com/words/{word}/similarTo
GEThttps://wordsapiv1.p.mashape.com/words/{word}/substanceOf
GEThttps://wordsapiv1.p.mashape.com/words/{word}/usageOf
GEThttps://wordsapiv1.p.mashape.com/words/{word}/antonyms
GEThttps://wordsapiv1.p.mashape.com/words/{word}/definitions
GEThttps://wordsapiv1.p.mashape.com/words/{word}/examples
GEThttps://wordsapiv1.p.mashape.com/words/{word}/frequency
GEThttps://wordsapiv1.p.mashape.com/words/{word}/pronunciation
GEThttps://wordsapiv1.p.mashape.com/words/?random=true
GEThttps://wordsapiv1.p.mashape.com/words/{word}/rhymes
GEThttps://wordsapiv1.p.mashape.com/words/
GEThttps://wordsapiv1.p.mashape.com/words/{word}/syllables
GEThttps://wordsapiv1.p.mashape.com/words/{word}/synonyms
GEThttps://wordsapiv1.p.mashape.com/words/{word}
